# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87419b7778de19b559b95fcb0f0b0999cfbb46b2c9dbb44f16ea328ccab0689ab69bb54c1ea8bb404cf4d865fc3b2b0d7d7934f187bb2739f0e1756c0693ab76
  google_static: ''

test:
  secret_key_base: 6a7b382a5629802b2faf9fc679d413f1b2c08064d7c3f722a9337dc5770bea0ea7077018977a8e95a9eba8fadd2553abe1e47d46374955b53cb36b95758b77d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_static: AIzaSyAGUZSRG0jaa4-xP1OmWdniAJbCAld9PZw
  google_oauth_client: 35775119515-7d5cl73gele709qsr5jbh220ko52u6g1.apps.googleusercontent.com
  google_oauth_secret: nYOE3-iMX4diPQGaEl9hk29U
